//USER STUFF
export const SET_USER = "SET_USER"
export const LOGOUT = "LOGOUT"


//JOBS STUFF
export const SET_API_KEYS = "SET_API_KEYS"
export const SET_JOBS_RETURNED_FROM_SEARCH = 'SET_JOBS_RETURNED_FROM_SEARCH'
export const SET_CURRENT_JOB = 'SET_CURRENT_JOB'
export const SET_USER_JOBS = 'SET_USER_JOBS'
export const SET_FAVORITE_CHECK = 'SET_FAVORITE_CHECK'
export const RESET_FAVORITE_CHECK = 'RESET_FAVORITE_CHECK'
export const SET_APPLIED_CHECK = 'SET_APPLIED_CHECK'
export const RESET_APPLIED_CHECK = 'RESET_APPLIED_CHECK'
export const SET_CURRENT_FAVORITE_JOB = 'SET_CURRENT_FAVORITE_JOB'


//NOTES STUFF
export const SET_NOTES = 'SET_NOTES'
export const SET_VIEW_NOTE = 'SET_VIEW_NOTE'
export const RESET_VIEW_NOTE = 'RESET_VIEW_NOTE'
export const SET_NEW_NOTE_JOB_ID = 'SET_NEW_NOTE_JOB_ID'
export const SET_CURRENT_NOTE = 'SET_CURRENT_NOTE'



//TODO STUFF
export const SET_TODOS = 'SET_TODOS'
export const SET_VIEW_TODO = 'SET_VIEW_TODO'
export const RESET_VIEW_TODO = 'RESET_VIEW_TODO'
export const SET_NEW_TODO_JOB_ID = 'SET_NEW_TODO_JOB_ID'
export const SET_CURRENT_TODO = 'SET_CURRENT_TODO'

