//USER STUFF
export const SET_USER = "SET_USER"
export const LOGOUT = "LOGOUT"


//JOBS STUFF
export const SET_API_KEYS = "SET_API_KEYS"
export const SET_JOBS_RETURNED_FROM_SEARCH = 'SET_JOBS_RETURNED_FROM_SEARCH'
export const SET_CURRENT_JOB = 'SET_CURRENT_JOB'
